version: '2'

services:
  php:
    container_name: alert_api_php
    build: ./docker/php
    links:
      - elasticsearch
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

  nginx:
    container_name: alert_api_nginx
    image: nginx:stable
    ports:
      - 80:80
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    container_name: alert_api_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alert-api
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306

  elasticsearch:
    image: elasticsearch