App\Model\Query:
  properties:
      latitude:
          - NotBlank: ~
          - LessThan: 90
          - GreaterThan: -90
      longitude:
          - NotBlank: ~
          - LessThan: 180
          - GreaterThan: -180

App\Entity\Type:
  properties:
      name:
          - NotBlank: ~
          - Length:
              max:   64
  constraints:
      - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name

App\Entity\Alert:
  properties:
      type:
          - NotBlank: ~
      latitude:
          - NotBlank: ~
          - LessThan: 90
          - GreaterThan: -90
      longitude:
          - NotBlank: ~
          - LessThan: 180
          - GreaterThan: -180

App\Entity\Confirmation:
  properties:
      value:
          - Type:
              type: bool