framework:
    secret: '%env(APP_SECRET)%'
    validation:    { enabled: true }

doctrine:
    dbal:
        driver: '%env(DATABASE_DRIVER)%'
        charset: UTF8
        url: '%env(DATABASE_URL)%'
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true
        mappings:
            App:
                prefix: AlertApi\Entity
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Resources/config/doctrine'
