specification:
  path:     /
  controller: App\Controller\ApplicationController::specification
  methods: [GET]

alert_search:
  path:     /alerts
  controller: App\Controller\AlertController::search
  methods: [GET]

alert_create:
  path:     /alerts
  controller: App\Controller\AlertController::save
  methods: [POST]

alert_confirmation:
  path:     /confirmations
  controller: App\Controller\ConfirmationController::save
  methods: [POST]