parameters:
    elasticsearch_host: 'elasticsearch'

services:
    _defaults:
        public: false

    alert_api.importer.csv:
        class: AlertApi\Importer\CsvImporter
        arguments:
            - '@doctrine.orm.entity_manager'

    alert_api.import_factory:
        class: AlertApi\ImporterFactory
        arguments:
            - '@alert_api.importer.csv'

    alert_api.command.import_command:
        class: AlertApi\Command\ImportCommand
        arguments:
            - '@alert_api.import_factory'
        tags: [console.command]

    elasticsearch.client:
        class: Elasticsearch\Client
        factory: ['Elasticsearch\ClientBuilder', fromConfig]
        arguments:
            - hosts:
                - '%elasticsearch_host%'
            - retries: 2

    alert_api.repository.elasticsearch.alert:
        public: true
        class: AlertApi\Repository\Elasticsearch\AlertRepository
        arguments:
            - '@elasticsearch.client'

    alert_api.command.mapping:
        class: AlertApi\Command\MappingCommand
        arguments:
            - '@elasticsearch.client'
        tags: [console.command]