parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    alert_api.importer.csv:
        class: App\Importer\CsvImporter
        arguments:
            - '@doctrine.orm.entity_manager'

    alert_api.import_factory:
        class: App\ImporterFactory
        arguments:
            - '@alert_api.importer.csv'

    alert_api.command.import_command:
        public: true
        class: App\Command\ImportCommand
        arguments:
            - '@alert_api.import_factory'
        tags: [console.command]