services:
    _defaults:
        public: false

    alert_api.repository.alert:
        public: true
        class: AlertApi\Repository\AlertRepository

    alert_api.importer.csv:
        class: AlertApi\Importer\CsvImporter
        arguments:
            - '@alert_api.repository.alert'

    alert_api.import_factory:
        class: AlertApi\ImporterFactory
        arguments:
            - '@alert_api.importer.csv'

    alert_api.command.import_command:
        class: AlertApi\Command\ImportCommand
        arguments:
            - '@alert_api.import_factory'
        tags: [console.command]
