openapi: 3.0.0

info:
  title: Alert API
  version: 1.0.0

servers:
  - url: http://localhost/
    description: Localy server

paths:
  /alerts:
    get:
      tags:
        - Alert
      summary: Return alerts by geographic data
      parameters:
        - in: query
          name: geodata
          description: Encoded geographic data structures in GeoJSON format
          schema:
            type: string
          required: true
      responses:
        '200':
          description: A JSON response with alerts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Alert"
    post:
      tags:
        - Alert
      summary: Report new alert
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                latitude:
                  type: string
                longitude:
                  type: string
      responses:
        '200':
          description: A JSON response with message
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"

  /confirmations:
    post:
      tags:
        - Confirmation
      summary: Confirm or refuse alert
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                alert:
                  type: "string"
                  format: "uuid"
                value:
                  type: boolean
      responses:
        '200':
          description: A JSON response with alert
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"

components:
  schemas:
    Alert:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        type:
          type: "string"
        latitude:
          type: "string"
        longitude:
          type: "string"
    Message:
      type: "object"
      properties:
        status:
          type: "string"
        message:
          type: "string"
