App\Entity\Type:
    type: entity
    table: type
    repositoryClass: App\Repository\Doctrine\TypeRepository
    id:
        id:
            type: uuid
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        name:
            column: name
            type: string
            nullable: false
            unique: true
            length: 64
    oneToMany:
         alerts:
             targetEntity: Alert
             mappedBy: type
             cascade: ["all"]

    lifecycleCallbacks: {  }